### ISSUE TITLE
Push code build lên branch gh-page và trỏ domain

### ISSUE THREAD

**Issue by baotnq** [vinaas/easywebhub#3]
@gattadesmond  em push thư mục /build tạo bởi metalsmith lên branch này nghe.

@nemesisqp  em tạo branch mới gh-pages, push nội dung bên trong thư mục /build lên 
và tạo subdomain trỏ tới github này
domain   handy-theme.lici.vn 
Link tham khảo : https://help.github.com/articles/using-a-custom-domain-with-github-pages/

Sau đó Phương hướng dẫn Hùng cách đồng bộ thư mục /build cho branch gh-pages như anh đã trao đổi nghe.

**Comment by baotnq** [comment]
Tham khảo:
http://gsferreira.com/archive/2014/06/update-github-pages-using-a-project-subfolder/

**Comment by nemesisqp** [comment]
Cái lệnh đó work đó anh
```
git subtree push --prefix build origin gh-pages
```

**Comment by baotnq** [comment]
@nemesisqp  @gattadesmond  cái lệnh trên đã chạy ok rồi , anh đã test trên source

https://github.com/easywebhub/easyweb-metalsmith

Và để dễ dàng, anh tạo thêm 1 file Public_gh-pages.bat để dễ dàng sử dụng, testing.
@nemesisqp  em cũng nên tìm cách làm các demo, test để khi review, sử dụng dễ dàng hơn nghe.

Close issue này
